### ISSUE TITLE
Publish 1.0

### ISSUE THREAD

**Issue by nox** [TyOverby/bincode#109]
Rust 1.15 is out, so that means we can have 1.0 now, right? :)

**Comment by dgriffen** [comment]
#104 and #103 should probably be closed first.

**Comment by aldanor** [comment]
A very minor thing, release-wise, does it make sense to relax deps version requirements down to minor number? E.g. it's currently 

```toml
[dependencies]
byteorder = "1.0.0"
num-traits = "0.1.32"

[dependencies.serde]
version = "0.9.*"

[dev-dependencies]
serde_derive = "0.9.*"
```

but I guess it could be just

```toml
[dependencies]
byteorder = "1.0"
num-traits = "0.1"

[dependencies.serde]
version = "0.9"

[dev-dependencies]
serde_derive = "0.9"
```
